#!/usr/bin/env bash
# slurm/run_local.sh — run a launch.sh-style config WITHOUT sbatch, directly
# on the current (allocated) node. Use when you already hold an exclusive
# Perlmutter node (e.g. via salloc / a JupyterHub kernel on a compute node)
# and the regular queue would otherwise be 3+ days.
#
# IMPORTANT — parallelism note (matches the production sbatch pattern):
#   desi-DLAGP.py hardcodes ``nproc_futures = 1``, so a single python process
#   only processes ONE spectra-16 file at a time, even if `max_workers > 8`.
#   Production gets node-wide parallelism by running 32 srun's in parallel,
#   each its own python (each on a different level2 slice). We mirror that
#   here by spawning N **parallel python processes**, each handling 1 file.
#
#   --parallel-files N  : number of python processes in parallel (default 4)
#   --max-workers W     : inner sample-level workers per python (default 64)
#                         Effective core usage: ≈ N × W on the same node.
#
# Usage:
#   bash slurm/run_local.sh slurm/configs/london0_y3.env \
#        --outdir /pscratch/sd/j/jibancat/runs/local-london/ \
#        --window 4 --parallel-files 4 --max-workers 64
#
# All allowed-write-area validation from launch.sh applies.

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <config.env> [--outdir PATH] [--start N] [--end N] [--window N] [--parallel-files N] [--max-workers W] [--dry-run]" >&2
    exit 2
fi

CONFIG_PATH="$1"; shift
START_OVERRIDE="" ; END_OVERRIDE="" ; WINDOW_OVERRIDE="" ; OUTDIR_OVERRIDE=""
WORKERS_OVERRIDE="" ; PARALLEL_FILES=4 ; DRY_RUN=0 ; POSTPROCESS=1

while [ $# -gt 0 ]; do
    case "$1" in
        --outdir)         OUTDIR_OVERRIDE="$2"; shift 2 ;;
        --start)          START_OVERRIDE="$2"; shift 2 ;;
        --end)            END_OVERRIDE="$2"; shift 2 ;;
        --window)         WINDOW_OVERRIDE="$2"; shift 2 ;;
        --max-workers)    WORKERS_OVERRIDE="$2"; shift 2 ;;
        --parallel-files) PARALLEL_FILES="$2"; shift 2 ;;
        --no-postprocess) POSTPROCESS=0; shift ;;
        --dry-run)        DRY_RUN=1; shift ;;
        *) echo "[run-local] unknown arg: $1" >&2; exit 2 ;;
    esac
done

# Resolve config (same logic as launch.sh)
if [ ! -f "$CONFIG_PATH" ]; then
    if [ -f "${REPO_ROOT}/${CONFIG_PATH}" ]; then
        CONFIG_PATH="${REPO_ROOT}/${CONFIG_PATH}"
    elif [ -f "${REPO_ROOT}/slurm/configs/${CONFIG_PATH}" ]; then
        CONFIG_PATH="${REPO_ROOT}/slurm/configs/${CONFIG_PATH}"
    else
        echo "[run-local] config not found: $CONFIG_PATH" >&2; exit 2
    fi
fi
# shellcheck disable=SC1090
source "$CONFIG_PATH"

[ -n "$OUTDIR_OVERRIDE" ]  && OUTDIR="$OUTDIR_OVERRIDE"
[ -n "$WINDOW_OVERRIDE" ]  && OUTER_WINDOW="$WINDOW_OVERRIDE"
[ -n "$WORKERS_OVERRIDE" ] && MAX_WORKERS="$WORKERS_OVERRIDE"

# Validate write area
ALLOWED_PREFIXES=(
    "/pscratch/sd/j/jibancat/"
    "/global/homes/j/jibancat/"
    "/global/cfs/cdirs/desicollab/users/jibancat/"
)
abs_outdir="$(readlink -m "$OUTDIR")"
ok=0
for p in "${ALLOWED_PREFIXES[@]}"; do
    case "$abs_outdir/" in "$p"*) ok=1; break ;; esac
done
if [ "$ok" -ne 1 ]; then
    echo "[run-local] REFUSING: OUTDIR=$abs_outdir is outside the allowed write roots" >&2
    exit 3
fi
OUTDIR="$abs_outdir"

[ "$DRY_RUN" -ne 1 ] && mkdir -p "$OUTDIR" "${OUTDIR}/logs"

# Snapshot the run's settings + a baseline reference for traceability
if [ "$DRY_RUN" -ne 1 ]; then
    cp -n "${REPO_ROOT}/slurm/configs/BASELINE.md" "${OUTDIR}/BASELINE.md" 2>/dev/null || true
    {
        echo "# Run settings — $(date -u +%FT%TZ)"
        echo
        echo "Generated by slurm/run_local.sh on \`$(hostname)\` (job ${SLURM_JOB_ID:-(none)})"
        echo
        echo "## Source config"
        echo "- file: \`$CONFIG_PATH\`"
        echo
        echo "## Resolved values"
        for v in MODE QSOCAT MOCKDIR OUTDIR LEARNED_FILE \
                 DLA_SAMPLES_FILE NUM_DLA_SAMPLES \
                 SUB_DLA_SAMPLES_FILE NUM_SUBDLA_SAMPLES \
                 MAX_DLAS SINGLE_ABSORBER_MODEL FILTER_LOW_LIKELIHOOD \
                 PREV_TAU_0 PREV_BETA DLAMBDA K \
                 LOADING_MIN_LAMBDA LOADING_MAX_LAMBDA \
                 NORMALIZATION_MIN_LAMBDA NORMALIZATION_MAX_LAMBDA \
                 MIN_LAMBDA MAX_LAMBDA NUM_FOREST_LINES NUM_LINES \
                 MAX_NOISE_VARIANCE BATCH_SIZE MAX_WORKERS BALMASK \
                 OUTER_MAX_INDEX OUTER_STEP OUTER_WINDOW \
                 ENABLE_TAU_EB TAU_EB_OBJECTIVE EARLY_STOP_MODE; do
            echo "- \`$v\` = \`${!v:-(unset)}\`"
        done
        echo
        echo "## Local parallelism"
        echo "- \`PARALLEL_FILES\` (this script) = $PARALLEL_FILES"
        echo "- \`MAX_WORKERS\` per python = $MAX_WORKERS"
        echo "- effective core use ≈ $((PARALLEL_FILES * MAX_WORKERS)) of $(nproc 2>/dev/null || echo '?') CPUs"
        echo
        echo "## Loop slice"
        echo "- \`LOOP_START\` = $LOOP_START"
        echo "- \`LOOP_END\` = $LOOP_END"
        echo "- 1 outer chunk per OUTER_STEP=$OUTER_STEP; window=$OUTER_WINDOW"
        echo
        echo "See [\`BASELINE.md\`](BASELINE.md) for the full baseline-vs-overrides table."
    } > "${OUTDIR}/RUN_SETTINGS.md"
fi

LOOP_START="${START_OVERRIDE:-0}"
LOOP_END="${END_OVERRIDE:-$OUTER_MAX_INDEX}"

echo "[run-local] config:         $CONFIG_PATH"
echo "[run-local] MODE=$MODE  OUTDIR=$OUTDIR"
echo "[run-local] parallel files: ${PARALLEL_FILES}   max_workers (inner)=${MAX_WORKERS}"
echo "[run-local] approx core use: $(( PARALLEL_FILES * MAX_WORKERS ))"
echo "[run-local] outer loop: ${LOOP_START} .. ${LOOP_END}  window=${OUTER_WINDOW}  step=${OUTER_STEP}"
nproc_machine=$(nproc 2>/dev/null || echo 256)
echo "[run-local] node has ${nproc_machine} CPUs"

# Build a (mode-dependent) python command for ONE single-file range
build_cmd() {
    local _idx_start="$1" _idx_end="$2"
    local cmd=(
        python "${REPO_ROOT}/desi-DLAGP.py"
        --qsocat "$QSOCAT"
        --release "$RELEASE"
        --program "$PROGRAM"
        --survey "$SURVEY"
        --outdir "$OUTDIR"
        --learned_file "$LEARNED_FILE"
        --catalog_name "$CATALOG_NAME"
        --los_catalog "$LOS_CATALOG"
        --dla_catalog "$DLA_CATALOG"
        --dla_samples_file "$DLA_SAMPLES_FILE"
        --sub_dla_samples_file "$SUB_DLA_SAMPLES_FILE"
        --min_z_separation "$MIN_Z_SEPARATION"
        --prev_tau_0 "$PREV_TAU_0"
        --prev_beta "$PREV_BETA"
        --max_dlas "$MAX_DLAS"
        --plot_figures "$PLOT_FIGURES"
        --filter_low_likelihood "$FILTER_LOW_LIKELIHOOD"
        --single_absorber_model "$SINGLE_ABSORBER_MODEL"
        --max_workers "$MAX_WORKERS"
        --batch_size "$BATCH_SIZE"
        --loading_min_lambda "$LOADING_MIN_LAMBDA"
        --loading_max_lambda "$LOADING_MAX_LAMBDA"
        --normalization_min_lambda "$NORMALIZATION_MIN_LAMBDA"
        --normalization_max_lambda "$NORMALIZATION_MAX_LAMBDA"
        --min_lambda "$MIN_LAMBDA"
        --max_lambda "$MAX_LAMBDA"
        --dlambda "$DLAMBDA"
        --k "$K"
        --num_dla_samples "$NUM_DLA_SAMPLES"
        --num_subdla_samples "$NUM_SUBDLA_SAMPLES"
        --max_noise_variance "$MAX_NOISE_VARIANCE"
        --num_forest_lines "$NUM_FOREST_LINES"
        --num_lines "$NUM_LINES"
        --figure_dir "$OUTDIR"
    )
    if [ "$MODE" = "loa" ]; then
        cmd+=(--hpx_start "$_idx_start" --hpx_end "$_idx_end")
    else
        cmd+=(--mocks --mockdir "$MOCKDIR" --level2_start "$_idx_start" --level2_end "$_idx_end")
    fi
    if [ "$BALMASK" = "true" ]; then
        cmd+=(--balmask)
    fi
    # τ-EB (per-spectrum empirical-Bayes τ_eff fit). Default off.
    if [ "${ENABLE_TAU_EB:-0}" = "1" ]; then
        cmd+=(--enable_tau_eb 1)
        if [ -n "${TAU_EB_FACTORS:-}" ]; then
            cmd+=(--tau_eb_factors ${TAU_EB_FACTORS})
        fi
        if [ -n "${TAU_EB_OBJECTIVE:-}" ]; then
            cmd+=(--tau_eb_objective "${TAU_EB_OBJECTIVE}")
        fi
        if [ "${TAU_EB_APPLY_HCD_MASK:-0}" = "1" ]; then
            cmd+=(--tau_eb_apply_hcd_mask 1)
        fi
    fi
    # Multi-DLA early-stop policy
    # (see docs/notes/2026-05-12_multidla_early_stop_bug.md)
    if [ -n "${EARLY_STOP_MODE:-}" ]; then
        cmd+=(--early_stop_mode "${EARLY_STOP_MODE}")
    fi
    # FILTER=1 truncated-sampler knobs
    # (see docs/notes/2026-05-13_filter1_knob_tuning.md and runbook §3.6)
    if [ -n "${FILTER_N_INITIAL_FLOOR:-}" ]; then
        cmd+=(--filter_n_initial_floor "${FILTER_N_INITIAL_FLOOR}")
    fi
    if [ "${FILTER_EMPTY_MASK_FALLTHROUGH:-0}" = "1" ]; then
        cmd+=(--filter_empty_mask_fallthrough 1)
    fi
    printf '%q ' "${cmd[@]}"
}

# Slice the [LOOP_START, LOOP_START + OUTER_WINDOW] range into 1-file chunks
# and run PARALLEL_FILES of them at a time (background &, then `wait`).
# Each python is one spectra-16 file → matches production's 1-file-per-srun shape.

TOTAL=$OUTER_WINDOW   # number of file-slots in this debug pass
echo "[run-local] processing ${TOTAL} single-file slices in waves of ${PARALLEL_FILES}"

declare -a pids
i=0
while [ $i -lt $TOTAL ]; do
    pids=()
    n_in_wave=0
    while [ $n_in_wave -lt $PARALLEL_FILES ] && [ $i -lt $TOTAL ]; do
        idx_start=$(( LOOP_START + i ))
        idx_end=$(( idx_start + 1 ))
        log_file="${OUTDIR}/logs/local_${idx_start}_${idx_end}.log"
        cmd_str=$(build_cmd "$idx_start" "$idx_end")
        echo "[run-local] $(date +%H:%M:%S) launching slice ${idx_start}..${idx_end}  log=${log_file##*/}"
        if [ "$DRY_RUN" -eq 1 ]; then
            echo "  $cmd_str"
        else
            (eval "$cmd_str" > "$log_file" 2>&1) &
            pids+=("$!")
        fi
        i=$((i + 1))
        n_in_wave=$((n_in_wave + 1))
    done
    if [ "$DRY_RUN" -ne 1 ] && [ ${#pids[@]} -gt 0 ]; then
        echo "[run-local] $(date +%H:%M:%S) waiting for wave of ${#pids[@]} python proc(s) ..."
        wait "${pids[@]}"
        echo "[run-local] $(date +%H:%M:%S) wave done."
    fi
done

echo "[run-local] all done."

# --- Postprocess: add downstream catalog flags to dlacat-*.fits -------------
# Runs add_dla_flags.py over the OUTDIR so the shipped catalog carries
# LYBETA / BAL flags (folded into DLAFLAG) plus the informational
# NHI_CONSISTENCY / PDLA_SATURATED / BF_BAND columns. Skip with
# --no-postprocess. Mock runs resolve the BAL catalog from MOCKDIR; if not
# found, the BAL flag is skipped. BF_BAND needs the run's processed h5
# (in OUTDIR/processed) + the DLA samples .mat; passed below.
if [ "$DRY_RUN" -ne 1 ] && [ "$POSTPROCESS" -eq 1 ]; then
    bal_path=""
    if [ -n "${MOCKDIR:-}" ] && [ -f "${MOCKDIR}/bal_cat.fits" ]; then
        bal_path="${MOCKDIR}/bal_cat.fits"
    fi
    pp_args=(--catalog-dir "$OUTDIR")
    if [ -n "$bal_path" ]; then
        pp_args+=(--bal-cat "$bal_path")
    else
        echo "[run-local] postprocess: no bal_cat.fits under MOCKDIR — skipping BAL_FLAG"
        pp_args+=(--no-bal-flag)
    fi
    # BF_BAND: pass the QMC samples file this run used (else add_dla_flags
    # skips BF_BAND gracefully).
    if [ -n "${DLA_SAMPLES_FILE:-}" ] && [ -f "${DLA_SAMPLES_FILE}" ]; then
        pp_args+=(--dla-samples-file "$DLA_SAMPLES_FILE")
    else
        echo "[run-local] postprocess: DLA_SAMPLES_FILE unset/missing — skipping BF_BAND"
    fi
    echo "[run-local] $(date +%H:%M:%S) postprocess: add_dla_flags.py ${pp_args[*]}"
    if python "${REPO_ROOT}/tools/postprocess/add_dla_flags.py" "${pp_args[@]}"; then
        echo "[run-local] postprocess done — dlacat-*.fits now carry DLAFLAG flags."
    else
        echo "[run-local] WARNING: postprocess failed; dlacat-*.fits are un-flagged." >&2
    fi
fi
