#!/usr/bin/env bash
# launch_phaseC_resp_pilot.sh — Phase-C response-calibration PILOT (Stage 1 gate).
#
# docs/PHASEC_CALIB_DESIGN.md §10 + PI rulings 2026-08-06 §11: the smallest run
# validating the anchored-injection → production-GP → contract-matching →
# response-measurement chain end-to-end, re-measuring per-spec cost, yields and
# variances. Production (Stage 2) is GATED on this pilot AND on explicit PI
# budget authorization (§12 — no envelope exists; do NOT launch Stage 2).
#
# Submits ONE production-config sbatch per pilot arm (arms already generated by
# injection/gen_phaseC_resp.py; this launcher does NOT generate):
#   prodlike : ~208 spec (BAL-veto-only substrate, HCD-neighbor z-veto 5000 km/s)
#   clean    : ~102 spec (environment probe)
# Cost: ~310 spec × ~167 CPU-s ≈ 14.4 CPU-h total.
#
# Usage:
#   bash slurm/greatlakes/production/launch_phaseC_resp_pilot.sh [--dry-run]
#   PHASEC_PILOT_ROOT=<root> ... (override the arm parent dir)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DRY_RUN=0; PASSTHRU=()
for a in "$@"; do
    case "$a" in
        --dry-run) DRY_RUN=1; PASSTHRU+=("$a") ;;
        *) PASSTHRU+=("$a") ;;
    esac
done

GL_SCRATCH="/scratch/cavestru_root/cavestru0/mfho"
PHASEC_PILOT_ROOT="${PHASEC_PILOT_ROOT:-${GL_SCRATCH}/phaseC_resp}"

for ARMNAME in pilot_prodlike pilot_clean; do
    ARM="${PHASEC_PILOT_ROOT}/${ARMNAME}"
    ARM_TREE="${ARM}/spectra-16"
    if [ ! -d "$ARM_TREE" ]; then
        echo "[phaseC-pilot] ERROR: arm tree absent: $ARM_TREE (generate first:" >&2
        echo "  python injection/gen_phaseC_resp.py --out $ARM ...)" >&2
        exit 1
    fi
    N_FILES=$(find "$ARM_TREE" -name 'spectra-16-*.fits' 2>/dev/null | wc -l)
    [ "${N_FILES:-0}" -ge 1 ] || { echo "[phaseC-pilot] ERROR: no spectra in $ARM_TREE" >&2; exit 1; }
    echo "[phaseC-pilot] arm=$ARMNAME  files=$N_FILES  -> one sbatch window [0,$N_FILES)"
    export PHASEC_ARM="$ARM"
    bash "${SCRIPT_DIR}/launch_gl.sh" phaseC_resp_gl_v1.env \
        --start 0 --end 0 --window "$N_FILES" --no-sleep "${PASSTHRU[@]}"
done
