"""joint_drop_count_validation.py — LLS-tier validation of the JOINT drop+count estimator
(`CDDF_analysis/hbi/joint_drop_count.py`) on the 2LPT-0 mock. Re-derivable, git-stamped —
replaces the plot-script literals the 2026-07-06 cross-check flagged (R0/band were never
guarded by re-execution). Reduce-only: NO inference, NO SLURM.

Builds the loa0 counting forward (nhi172 molly, op-cut to 17.2, fit_floor=19.5, pspline) EXACTLY
as the referee cache builder did, plus a PHYSICAL drop tau_hat(z912) summed DIRECTLY over the mock
HCD truth catalog (NOT generated by drop_tau_model — so the top-knot overflow, which cancels only
in a self-consistent synthetic drop, is genuinely exercised). Then:

  * HEADLINE (prior-free): lambda_mfp / tau_eff,LL. Fit kappa_912 to the truth tau_hat AND to the
    joint-MAP tau_model(theta), invert to lambda_mfp (proper Mpc), report R0_lambda = est/truth and
    the drop-fit reduced chi^2. This is the robust deliverable — a near-direct readout of the drop.
  * DERIVED (shape-limited): ell(X)[17.2,19.5). Report the joint-MAP ell + R0 for a canonical shape,
    AND the shape-marginalized band [q16,q50,q84] (lls_shape_marginalized_band, committed defaults
    lam_spline=60 / n_lap=400, single-PL slopes -1.9/-1.5/-1.1). The band is prior/shape-limited by
    construction (counts+drop under-determine ell — the panel's F1); truth is quoted for context but
    "brackets truth" is necessary-not-sufficient.
  * SANITY: drop=None reproduces the frozen counting-only fit; DLA-tier dN/dX(>=20.3) R0 ~ 1.1.

MOCK values only (public-OK). Real-LOA lambda_mfp/ell are private + PI-unblinding-gated.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

import numpy as np

# repo root = 4 dirnames up (lls -> diagnostics -> CDDF_analysis -> <repo>).
_REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from astropy.table import Table  # noqa: E402

from CDDF_analysis.hbi import ab_loa0_fp_baseline as AB  # noqa: E402
from CDDF_analysis.diagnostics.lls import lls_loa0_validation as LV  # noqa: E402
from CDDF_analysis.hbi.cddf_catalog_hbi import (  # noqa: E402
    v3x_build_forward, truth_reductions, v3x_reduce, v3x_f_of_N,
    _v3x_spline_knots, _bspline_basis)
import CDDF_analysis.hbi.joint_drop_count as J  # noqa: E402
from CDDF_analysis.lyc import opacity as LYC  # noqa: E402

DEFAULT_OUT_JSON = os.path.join(_REPO, "CDDF_analysis", "hbi", "joint_mock_validation.json")

# drop geometry (mock): effective QSO redshift + observed-limit redshift grid, matched to the
# HCD-only injection (beta=3.0, sigma912=6.35e-18). z_qso caps the mock's ~3.5-3.8 support.
Z_QSO = 3.5
BETA = 3.0
Z912 = np.linspace(2.6, 3.35, 8)
SHAPE_SLOPES = (-1.9, -1.5, -1.1)     # single-PL LLS shape hypotheses pooled for the band


def _git_commit():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=_REPO,
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception as e:  # noqa: BLE001
        print(f"  [WARN] _git_commit() failed ({type(e).__name__}: {e})", file=sys.stderr)
        return "unknown"


def _build_forward():
    """loa0 counting forward + truth reductions (mirrors the referee cache builder)."""
    args = LV._Args(LV.NHI172_MOLLY)
    args.family = "pspline"
    args.fit_floor = 19.5
    ing = AB.build_ingredients(args, "loa0", loa0_product=args.loa0_product)
    cfg = ing["cfg"]
    cfg.v3_family = "pspline"
    cfg.v3_logN_fit_floor = 19.5
    cfg.v3_n_spline_knots = 7
    cfg.v3_lambda_spline = 1.0
    cfg.v3_sub_floor_ridge_lam = 0.0
    cfg._posterior_kernel_2d = None
    ef = ing["estimator_fn"]
    qsp = ef.keywords["qso_per_sl"]
    Xc = ef.keywords["Xcalc"]
    lo, hi, Nb, dNb = ing["logN_lo"], ing["logN_hi"], ing["N_b"], ing["dN_b"]
    fwd = v3x_build_forward(cfg, ing["cat_cut"], ing["good_mask"], ing["mm"], qsp,
                            lo, hi, Nb, dNb, Xc)
    tr = truth_reductions(cfg, ing["truth_cut"], lo, hi, Nb, dNb, ing["X_tot"])
    return cfg, fwd, tr, ing, lo, hi, Nb, dNb


def _physical_drop():
    """tau_hat(z912) summed DIRECTLY over the mock HCD truth catalog (Campbell/Meiksin-Madau
    tau_eff = E[sum_k (1-e^{-tau_k})]): the 'measured' drop, independent of drop_tau_model, so
    the top-knot fix is exercised (a self-consistent synthetic drop would cancel it)."""
    hcd = Table.read(AB.DEF_TRUTH)
    zc = Table.read(os.path.join(os.path.dirname(AB.DEF_TRUTH), "zcat.fits"))
    zq = {int(t): float(z) for t, z in zip(zc["TARGETID"], zc["Z"])}
    n_sl = sum(1 for z in zq.values() if z >= 3.0)
    slset = {int(t) for t in zc["TARGETID"] if zq.get(int(t), 0.0) >= 3.0}
    keep = np.array([int(t) in slset for t in hcd["TARGETID"]])
    aN = (10.0 ** np.asarray(hcd["NHI"], float))[keep]
    az = np.asarray(hcd["Z"], float)[keep]
    sg = LYC.SIGMA_912
    tau_hat = np.array([
        float(np.sum(1.0 - np.exp(-(aN[m] * sg * ((1 + zz) / (1 + az[m])) ** BETA)))) / n_sl
        for zz in Z912 for m in [(az > zz) & (az < Z_QSO)]])
    return tau_hat, n_sl


def _shape_priors(f_truth, lo, hi):
    mid = 0.5 * (lo + hi)
    f192 = np.log10(max(f_truth[np.argmin(np.abs(mid - 19.2))], 1e-300))
    anch = [17.5, 18.5, 19.2]
    return [J.SubLLSPrior(anch, [f192 + sl * (a - 19.2) for a in anch], [0.15, 0.15, 0.10])
            for sl in SHAPE_SLOPES]


def run(n_lap: int, lam_spline: float) -> dict:
    t0 = time.time()
    cfg, fwd, tr, ing, lo, hi, Nb, dNb = _build_forward()
    fine = fwd["fine"]
    f_truth = np.asarray(tr["f_truth"], float)
    sel = (lo >= 17.2 - 1e-9) & (hi <= 19.5 + 1e-9)
    true_ell = float(np.nansum(f_truth[sel] * dNb[sel]))
    print(f"[build {time.time()-t0:.0f}s] true_ell[17.2,19.5)={true_ell:.4f}  "
          f"A_full{fwd['A_full'].shape}", flush=True)

    tau_hat, n_sl = _physical_drop()
    sigma = np.maximum(0.10 * tau_hat, 0.02)
    drop = J.DropData(Z912, tau_hat, sigma, Z_QSO, sigma912=LYC.SIGMA_912, beta=BETA, logN_lo=17.2)

    # ---- SANITY: drop=None == frozen counting-only; DLA-tier dN/dX(>=20.3) R0 ----
    fj0 = J.fit_joint(fwd, "pspline", cfg, None, n_restart=8, seed=0)
    red0 = J.reduce_theta(fj0["theta_map"], fwd, "pspline", cfg)
    dndx_e = float(red0["dndx_total"][20.3]); dndx_t = float(tr["dndx_total"][20.3])
    r0_dla = dndx_e / dndx_t if dndx_t > 0 else np.nan
    print(f"[sanity] counting-only dN/dX(>=20.3) R0={r0_dla:.3f}  (est {dndx_e:.4g} / truth {dndx_t:.4g})",
          flush=True)

    # ---- HEADLINE: lambda_mfp / tau_eff,LL (prior-free) ----
    cosmo = LYC.Cosmology(Om=float(getattr(cfg, "Omega_m", 0.279)))
    kap_t = LYC.fit_kappa(Z912, tau_hat, Z_QSO, beta=BETA, cosmo=cosmo)
    lam_t = LYC.lambda_mfp_from_kappa(kap_t, Z_QSO, beta=BETA, cosmo=cosmo)
    # joint MAP under a canonical (middle) shape prior, then read the drop it implies
    shapes = _shape_priors(f_truth, lo, hi)
    fj = J.fit_joint(fwd, "pspline", cfg, drop, sub_lls=shapes[1], lam_spline=lam_spline, seed=1)
    tau_est = J.drop_tau_model(fj["theta_map"], "pspline", cfg, Z912, Z_QSO,
                               sigma912=LYC.SIGMA_912, beta=BETA, logN_lo=17.2)
    kap_e = LYC.fit_kappa(Z912, tau_est, Z_QSO, beta=BETA, cosmo=cosmo)
    lam_e = LYC.lambda_mfp_from_kappa(kap_e, Z_QSO, beta=BETA, cosmo=cosmo)
    chi2 = float(np.sum(((tau_est - tau_hat) / sigma) ** 2)) / Z912.size
    map_ell = float(v3x_reduce(cfg, fj["theta_map"], fine, "pspline", fwd.get("M_meta"))["ell_lls_extrap"])
    print(f"[headline] lambda_mfp truth={lam_t:.1f} est={lam_e:.1f} Mpc  R0={lam_e/lam_t:.3f}  "
          f"drop chi2/dof={chi2:.3f}  kappa_t={kap_t:.4g} kappa_e={kap_e:.4g}", flush=True)
    print(f"[derived]  canonical-shape MAP ell={map_ell:.4f}  R0={map_ell/true_ell:.3f}", flush=True)

    # ---- DERIVED: shape-marginalized ell band (committed defaults) ----
    band = J.lls_shape_marginalized_band(fwd, cfg, drop, shapes, lam_spline=lam_spline, n_lap=n_lap)
    b = band["band"]
    print(f"[band] ell[17.2,19.5) shape-marg [q16,q50,q84]={np.round(b,4)}  R0(q50)={b[1]/true_ell:.3f}"
          f"  truth_in_band={b[0] <= true_ell <= b[2]}  map_spread={band['map_spread']:.3g}", flush=True)
    for p in band["per_shape"]:
        print(f"    shape{p['shape']}(esc_lam={p['lam_spline']:.0f}): map_ell={p['map_ell']:.4g} "
              f"cond={p['cond']:.1e} q={np.round(p['q'],4)}", flush=True)

    return dict(
        wall_s=round(time.time() - t0, 1),
        true_ell=true_ell, n_sl_drop=int(n_sl),
        sanity=dict(dla_dndx_est=dndx_e, dla_dndx_truth=dndx_t, r0_dla_dndx_203=r0_dla),
        headline=dict(lambda_mfp_truth_Mpc=lam_t, lambda_mfp_est_Mpc=lam_e,
                      r0_lambda_mfp=(lam_e / lam_t) if lam_t else np.nan,
                      kappa912_truth=kap_t, kappa912_est=kap_e,
                      drop_chi2_per_dof=chi2, beta=BETA, sigma912=LYC.SIGMA_912),
        derived=dict(canonical_map_ell=map_ell, r0_canonical=map_ell / true_ell,
                     band_q16_q50_q84=b, q=band["q"], r0_band_q50=b[1] / true_ell,
                     truth_in_band=bool(b[0] <= true_ell <= b[2]),
                     map_spread=band["map_spread"], per_shape=band["per_shape"],
                     shape_slopes=list(SHAPE_SLOPES), lam_spline=lam_spline, n_lap=n_lap),
        tau_hat=tau_hat.tolist(), tau_est=tau_est.tolist(), z912=Z912.tolist(), z_qso=Z_QSO,
    )


def main(a):
    t = time.time()
    res = run(a.n_lap, a.lam_spline)
    out = dict(
        metadata=dict(
            what="LLS-tier JOINT drop+count estimator validation on the 2LPT-0 mock: prior-free "
                 "lambda_mfp/tau_eff,LL headline + shape-marginalized ell(X)[17.2,19.5) band",
            mock="2LPT-0 (loa-124); MOCK recovery values (public-OK), NOT real-LOA",
            code_commit=_git_commit(),
            wallclock_s=round(time.time() - t, 1),
            rederive="python CDDF_analysis/diagnostics/lls/joint_drop_count_validation.py --force",
            estimator="CDDF_analysis/hbi/joint_drop_count.py (fit_joint / joint_laplace / "
                      "lls_shape_marginalized_band); drop is a PHYSICAL direct-sum over HCD truth "
                      "(exercises the _clamp_drop_grid top-knot fix).",
            note="HEADLINE = lambda_mfp/tau_eff,LL (prior-free, R0_lambda~1). ell(X)[17.2,19.5) is a "
                 "DERIVED, shape/prior-limited band (counts+drop under-determine it — review F1); "
                 "R0(q50) is NOT expected ~1 and 'truth_in_band' is necessary-not-sufficient. "
                 "Omega_HI(LLS) is off-headline (too slope-sensitive). FP is CARRIED (loa0) — the "
                 "band holds lam_fp/mu_fp fixed, so it has no FP width (add the loa0<->purity "
                 "bracket externally).",
        ),
        result=res,
    )
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    if os.path.exists(a.out) and not a.force:
        print(f"[skip-json] {a.out} exists (pass --force to overwrite).")
    else:
        with open(a.out, "w") as fh:
            json.dump(out, fh, indent=2, default=float)
        print(f"[saved-json] {a.out}  code_commit={out['metadata']['code_commit']}  "
              f"({out['metadata']['wallclock_s']:.0f}s)")
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=DEFAULT_OUT_JSON)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--n-lap", type=int, default=400, dest="n_lap",
                    help="Laplace draws per shape (committed default 400).")
    ap.add_argument("--lam-spline", type=float, default=60.0, dest="lam_spline",
                    help="curvature penalty (committed band default 60).")
    main(ap.parse_args())
